// Definición de slots ("blanks") disponibles para armar un prompt.
// kind: 'subject' -> puede ser el sujeto de la frase (se usa capitalizado tal cual, sin conector)
//                     o, si no es el sujeto elegido, se antepone `connector`.
//       'clause'  -> siempre se agrega como cláusula tras una coma.
const WTD_SLOTS = [
  { id: 'personaje', label: 'Personaje', icon: 'assets/icons/el-personaje.svg', kind: 'subject', connector: 'junto a' },
  { id: 'criatura',  label: 'Criatura',  icon: 'assets/icons/el-criatura.svg',  kind: 'subject', connector: 'junto a' },
  { id: 'animal',    label: 'Animal',    icon: 'assets/icons/el-animal.svg',    kind: 'subject', connector: 'acompañado de' },
  { id: 'objeto',    label: 'Objeto',    icon: 'assets/icons/el-objeto.svg',    kind: 'subject', connector: 'cargando' },
  { id: 'ropa',      label: 'Ropa',      icon: 'assets/icons/el-ropa.svg',      kind: 'clause' },
  { id: 'accesorio', label: 'Accesorio', icon: 'assets/icons/el-accesorio.svg', kind: 'clause' },
  { id: 'atributo',  label: 'Atributo',  icon: 'assets/icons/el-atributo.svg',  kind: 'clause' },
  { id: 'habilidad', label: 'Habilidad', icon: 'assets/icons/el-habilidad.svg', kind: 'clause' },
  { id: 'vehiculo',  label: 'Vehículo',  icon: 'assets/icons/el-vehiculo.svg',  kind: 'subject', connector: 'sobre' },
  { id: 'arma',      label: 'Arma',      icon: 'assets/icons/el-arma.svg',      kind: 'clause' },
  { id: 'planta',    label: 'Planta',    icon: 'assets/icons/el-planta.svg',    kind: 'clause' },
  { id: 'comida',    label: 'Comida',    icon: 'assets/icons/el-comida.svg',    kind: 'clause' },
  { id: 'lugar',     label: 'Lugar',     icon: 'assets/icons/el-lugar.svg',     kind: 'clause' },
  { id: 'clima',     label: 'Clima',     icon: 'assets/icons/el-clima.svg',     kind: 'clause' },
  { id: 'material',  label: 'Material',  icon: 'assets/icons/el-material.svg', kind: 'clause' },
  { id: 'accion',    label: 'Acción',    icon: 'assets/icons/el-accion.svg',   kind: 'clause' },
];

// Orden de prioridad para elegir el sujeto principal de la frase.
const WTD_SUBJECT_PRIORITY = ['personaje', 'criatura', 'animal', 'vehiculo', 'objeto'];

// Sujeto genérico de respaldo, si el usuario no elige ningún slot tipo "subject".
const WTD_FALLBACK_SUBJECTS = ['Una escena'];

const WTD_CATEGORIES = [
  {
    id: 'fantasia',
    name: 'Fantasía medieval',
    icon: 'assets/icons/cat-fantasia.svg',
    banks: {
      personaje: [
        "un caballero errante",
        "una hechicera del bosque",
        "un herrero real",
        "un juglar itinerante",
        "una princesa guerrera",
        "un alquimista excéntrico",
        "un cazador de dragones",
        "un aprendiz de mago",
        "un elfo",
      ],
      criatura: [
        "un dragón anciano",
        "un ogro de las montañas",
        "una arpía de alas doradas",
        "un trasgo de las cuevas",
        "un unicornio",
        "un grifo",
        "una hada del bosque",
        "un basilisco",
      ],
      animal: [
        "un caballo blanco",
        "un halcón peregrino",
        "un lobo gris",
        "un cuervo negro",
        "un ciervo blanco",
        "una cabra montés",
        "un búho nival",
        "un zorro rojo",
      ],
      objeto: [
        "un pergamino enrollado",
        "una llave de bronce",
        "un cofre pequeño",
        "un candelabro de hierro",
        "una varita de madera tallada",
        "un mapa del tesoro",
        "una poción en un frasco",
        "un libro de hechizos antiguo",
      ],
      ropa: [
        "con una capa raída",
        "con una túnica de terciopelo",
        "con una armadura oxidada",
        "con un manto bordado",
        "con una capucha oscura",
        "con una falda de cuero",
        "con botas de siete leguas",
        "con un vestido de gala élfico",
      ],
      accesorio: [
        "con un amuleto de piedra",
        "con un anillo de sello",
        "con una corona de laurel",
        "con unos guantes de cuero fino",
        "con una diadema de plata",
        "con un colgante en forma de dragón",
        "con un cinturón con bolsas de pociones",
        "con una capa con broche dorado",
      ],
      atributo: [
        "con una cicatriz en forma de estrella",
        "con ojos que brillan en la oscuridad",
        "con una cola hecha de fuego frío",
        "con la piel cubierta de escamas doradas",
        "con alas de dragón en la espalda",
        "con una marca de nacimiento en forma de luna",
        "con el cabello que cambia de color",
        "con una voz que hipnotiza",
      ],
      habilidad: [
        "que puede lanzar hechizos de fuego",
        "que puede hablar con los animales",
        "que tiene fuerza sobrehumana",
        "que puede volverse invisible",
        "que puede resucitar a los muertos",
        "que domina la alquimia",
        "que puede leer mentes",
        "que convoca tormentas",
      ],
      vehiculo: [
        "una carreta de madera",
        "un carruaje real",
        "una balsa de troncos",
        "un carro de guerra",
        "una canoa élfica",
        "un trineo tirado por lobos",
        "una alfombra voladora",
        "un barco pirata de madera",
      ],
      arma: [
        "con una espada de doble filo",
        "con un arco largo",
        "con una lanza de roble",
        "con un hacha de guerra",
        "con una daga envenenada",
        "con un báculo de mago",
        "con una ballesta",
        "con un mazo de guerra",
      ],
      planta: [
        "rodeado de enredaderas espinosas",
        "junto a un roble centenario",
        "entre flores silvestres moradas",
        "cerca de un árbol retorcido sin hojas",
        "entre hongos luminosos",
        "junto a un árbol que habla",
        "rodeado de espinas mágicas",
        "entre lirios negros",
      ],
      comida: [
        "sosteniendo una jarra de cerveza",
        "comiendo un trozo de pan con queso",
        "con un cuenco de estofado humeante",
        "sosteniendo una manzana roja",
        "sosteniendo un cuerno de vino",
        "comiendo un pastel de carne",
        "con un plato de queso y uvas",
        "sosteniendo miel en un frasco de barro",
      ],
      lugar: [
        "frente a un castillo en ruinas",
        "dentro de una taberna iluminada por velas",
        "en lo alto de una torre de piedra",
        "junto a un puente de piedra sobre un río",
        "dentro de un laberinto de piedra",
        "en un mercado de un pueblo medieval",
        "frente a una cueva de dragón",
        "en las ruinas de un templo olvidado",
      ],
      clima: [
        "bajo una tormenta de rayos",
        "con niebla espesa cubriendo el suelo",
        "durante una nevada silenciosa",
        "bajo un cielo rojizo al atardecer",
        "bajo una llovizna mágica que brilla",
        "con vientos helados del norte",
        "durante un eclipse",
        "bajo la luz de dos lunas",
      ],
      material: [
        "hecho de oro macizo",
        "hecho de piedra tallada",
        "hecho de madera de roble",
        "hecho de hierro forjado",
        "hecho de plata élfica",
        "hecho de cristal encantado",
        "hecho de cuero curtido",
        "hecho de mithril",
      ],
      accion: [
        "mientras desenvaina su espada",
        "mientras lee un libro de hechizos",
        "mientras cabalga a toda velocidad",
        "mientras enciende una hoguera",
        "mientras prepara una poción",
        "mientras monta guardia en la muralla",
        "mientras negocia con un mercader",
        "mientras invoca un hechizo",
      ],
    },
  },
  {
    id: 'editorial',
    name: 'Editorial y cartoon',
    icon: 'assets/icons/cat-editorial.svg',
    banks: {
      personaje: [
        "un político con cara de circunstancia",
        "una abuela chismosa",
        "un oficinista estresado",
        "un influencer exagerado",
        "un repartidor apurado",
        "una mamá multitasking",
        "un turista perdido",
        "un vendedor ambulante",
      ],
      criatura: [
        "un monstruo de closet tímido",
        "un fantasma torpe",
        "un duende de oficina",
        "un extraterrestre confundido",
        "un monstruo debajo de la cama asustado de la luz",
        "un yeti tímido de oficina",
        "un dinosaurio de peluche vivo",
        "un robot doméstico anticuado",
      ],
      animal: [
        "un gato gordo",
        "un perro salchicha",
        "un pingüino regordete",
        "una gallina despeinada",
        "un loro imitador",
        "un hámster en una rueda",
        "un caniche peinado en exceso",
        "un pez dorado saltarín",
      ],
      objeto: [
        "un maletín gastado",
        "una taza de café gigante",
        "un paraguas roto",
        "un teléfono con la pantalla rota",
        "un termo de café derramado",
        "una carpeta llena de papeles",
        "un control remoto perdido",
        "una calculadora vieja",
      ],
      ropa: [
        "con una corbata torcida",
        "con una bata de baño",
        "con un traje tres tallas más grande",
        "con calcetines de rombos desparejados",
        "con pantuflas en la oficina",
        "con un chaleco de seguridad naranja",
        "con una gorra al revés",
        "con medias que no combinan",
      ],
      accesorio: [
        "con un reloj de pulsera enorme",
        "con una placa de identificación torcida",
        "con unos audífonos gigantes",
        "con un prendedor con forma de dona",
        "con una libreta llena de post-its",
        "con audífonos inalámbricos perdidos",
        "con un botón de pánico en el llavero",
        "con una insignia de empleado del mes",
      ],
      atributo: [
        "con una papada enorme",
        "con lentes gruesos que agrandan los ojos",
        "con una sonrisa nerviosa exagerada",
        "con las cejas permanentemente levantadas",
        "con los pies hinchados de tanto caminar",
        "con manchas de café en la camisa",
        "con un tic nervioso en el ojo",
        "con el estómago que suena fuerte",
      ],
      habilidad: [
        "que siempre llega tarde a todo",
        "que se tropieza con sus propios pies",
        "que grita en las reuniones",
        "que duerme con los ojos abiertos",
        "que confunde los nombres de todos",
        "que hace chistes malos en momentos serios",
        "que se queda dormido en las juntas",
        "que siempre pierde las llaves",
      ],
      vehiculo: [
        "un auto viejo y abollado",
        "una bicicleta oxidada",
        "un scooter eléctrico pequeño",
        "una patineta desgastada",
        "un carrito de supermercado con una rueda chueca",
        "una moto de reparto",
        "un auto compacto mal estacionado",
        "una silla de oficina con ruedas",
      ],
      arma: [
        "con un paraguas como si fuera espada",
        "con un matamoscas gigante",
        "con un megáfono",
        "con una regla de madera como arma improvisada",
        "con un cuchillo de plástico para cortar torta",
        "con una grapadora como arma improvisada",
        "con un extintor",
        "con una escoba",
      ],
      planta: [
        "junto a una planta de oficina medio muerta",
        "entre macetas de plástico desordenadas",
        "cerca de un árbol lleno de globos perdidos",
        "con un cactus torcido en el escritorio",
        "junto a una planta artificial polvorienta",
        "entre flores de plástico en un jarrón",
        "cerca de un árbol de navidad fuera de temporada",
        "con hierbas secas mal cuidadas",
      ],
      comida: [
        "sosteniendo una dona a medio comer",
        "con un vaso de café para llevar",
        "comiendo fideos instantáneos de un vaso",
        "sosteniendo una hamburguesa gigante",
        "sosteniendo palomitas de microondas quemadas",
        "con una pizza fría del día anterior",
        "comiendo cereal directo de la caja",
        "sosteniendo un batido derramándose",
      ],
      lugar: [
        "en medio de un embotellamiento",
        "dentro de una oficina con cubículos apretados",
        "en la fila del supermercado",
        "en una sala de espera abarrotada",
        "en la caja del supermercado",
        "frente a una máquina expendedora rota",
        "en el estacionamiento del mall",
        "dentro de un ascensor lleno",
      ],
      clima: [
        "bajo un sol que derrite el asfalto",
        "con lluvia que arruina el peinado",
        "en un día ventoso que vuela los papeles",
        "bajo un smog espeso",
        "bajo el aire acondicionado que no funciona",
        "con calor húmedo pegajoso",
        "en una ola de frío inesperada",
        "bajo un ventilador que hace ruido",
      ],
      material: [
        "hecho de cartón corrugado",
        "hecho de plástico barato",
        "hecho de goma elástica",
        "hecho de papel reciclado",
        "hecho de espuma de poliestireno",
        "hecho de silicona",
        "hecho de vidrio templado",
        "hecho de fieltro",
      ],
      accion: [
        "mientras revisa el celular sin parar",
        "mientras derrama el café encima",
        "mientras discute por teléfono",
        "mientras firma papeles sin leerlos",
        "mientras intenta abrir un frasco que no cede",
        "mientras busca estacionamiento",
        "mientras hace fila para el baño",
        "mientras arregla la impresora",
      ],
    },
  },
  {
    id: 'cienciaficcion',
    name: 'Ciencia Ficción',
    icon: 'assets/icons/cat-cienciaficcion.svg',
    banks: {
      personaje: [
        "un piloto de nave espacial",
        "una científica genética",
        "un explorador de otro planeta",
        "un soldado cibernético",
        "una androide con emociones",
        "un cazarrecompensas espacial",
        "un ingeniero de terraformación",
        "una comandante de flota",
      ],
      criatura: [
        "un alienígena de tres ojos",
        "una criatura mutante radiactiva",
        "un enjambre de nanobots con forma animal",
        "un depredador de otro planeta",
        "un alien parásito",
        "un robot gigante de combate",
        "una criatura acuática bioluminiscente",
        "un enjambre de drones con conciencia propia",
      ],
      animal: [
        "un gato blanco",
        "un cuervo gris",
        "un perro pequeño",
        "un halcón marrón",
        "un perro con prótesis robóticas",
        "un gato con collar rastreador",
        "un ave migratoria modificada",
        "un pez con branquias artificiales",
      ],
      objeto: [
        "un escáner portátil",
        "un dispositivo holográfico",
        "una esfera de energía",
        "un mapa estelar digital",
        "un núcleo de energía portátil",
        "un chip de memoria",
        "una llave criptográfica",
        "un dron de bolsillo",
      ],
      ropa: [
        "con un traje espacial ajustado",
        "con una chaqueta futurista con luces led",
        "con un uniforme militar espacial",
        "con una bata de laboratorio",
        "con un exoesqueleto ligero",
        "con una capa térmica reflectante",
        "con botas magnéticas",
        "con guantes aislantes de radiación",
      ],
      accesorio: [
        "con un visor de realidad aumentada",
        "con un implante en la sien",
        "con un collar con pantalla digital",
        "con guantes tecnológicos con botones",
        "con un chip neural en la nuca",
        "con lentes de escaneo biométrico",
        "con un brazalete de navegación",
        "con auriculares de traducción universal",
      ],
      atributo: [
        "con un brazo biónico",
        "con ojos que emiten luz azul",
        "con piel metálica",
        "con un tercer ojo en la frente",
        "con un ojo cibernético",
        "con venas que brillan de energía",
        "con la mitad del cuerpo robótica",
        "con piel translúcida bioluminiscente",
      ],
      habilidad: [
        "que puede teletransportarse",
        "que controla la tecnología con la mente",
        "que tiene visión de rayos x",
        "que puede hackear cualquier sistema",
        "que puede fusionar su mente con máquinas",
        "que controla la gravedad",
        "que puede clonarse a sí mismo",
        "que predice fallas mecánicas antes de que ocurran",
      ],
      vehiculo: [
        "una nave espacial plateada",
        "un vehículo flotante",
        "un rover todo terreno",
        "una moto propulsada por reactores",
        "un traje mecha",
        "una cápsula de escape",
        "un dron de carga",
        "un submarino de exploración profunda",
      ],
      arma: [
        "con una pistola láser",
        "con un sable de energía",
        "con un lanzallamas de plasma",
        "con un rifle de pulsos",
        "con un cañón de iones",
        "con una espada vibradora de energía",
        "con un dron de ataque",
        "con guantes electromagnéticos",
      ],
      planta: [
        "entre plantas bioluminiscentes",
        "cerca de árboles con hojas metálicas",
        "junto a un jardín hidropónico",
        "rodeado de esporas flotantes",
        "entre cultivos verticales automatizados",
        "cerca de árboles clonados genéticamente",
        "junto a algas bioluminiscentes",
        "rodeado de flora extraterrestre desconocida",
      ],
      comida: [
        "sosteniendo una bebida energética futurista",
        "comiendo una pastilla de comida concentrada",
        "con un tubo de nutrientes",
        "sosteniendo fruta cultivada en un invernadero espacial",
        "sosteniendo un cubo de proteína sintética",
        "con una bebida de algas fermentadas",
        "comiendo insectos cultivados en laboratorio",
        "sosteniendo fruta impresa en 3D",
      ],
      lugar: [
        "dentro de una nave espacial",
        "en una estación orbital",
        "sobre la superficie de un planeta desértico",
        "en un laboratorio futurista lleno de pantallas",
        "en una colonia subterránea marciana",
        "dentro de un ascensor espacial",
        "en un mercado alienígena",
        "en las ruinas de una civilización extinta",
      ],
      clima: [
        "bajo una lluvia ácida",
        "en medio de una tormenta de asteroides",
        "con gravedad reducida flotando en el aire",
        "bajo dos soles brillantes",
        "bajo cielos con dos lunas visibles",
        "en medio de una tormenta electromagnética",
        "con nieve de otro color",
        "bajo auroras artificiales generadas por la ciudad",
      ],
      material: [
        "hecho de metal cromado",
        "hecho de fibra de carbono",
        "hecho de vidrio reforzado",
        "hecho de aleación desconocida",
        "hecho de nanofibra autorreparable",
        "hecho de titanio espacial",
        "hecho de plasma condensado",
        "hecho de polímero transparente",
      ],
      accion: [
        "mientras pilota una nave",
        "mientras repara un robot",
        "mientras analiza datos en una pantalla holográfica",
        "mientras escapa de un peligro",
        "mientras programa una inteligencia artificial",
        "mientras navega por el espacio profundo",
        "mientras negocia con una especie alienígena",
        "mientras repara un traje espacial dañado",
      ],
    },
  },
  {
    id: 'terror',
    name: 'Terror y misterio',
    icon: 'assets/icons/cat-terror.svg',
    banks: {
      personaje: [
        "un doctor de mirada perturbadora",
        "una niña que no parpadea",
        "un enterrador solitario",
        "un paciente de manicomio abandonado",
        "una monja poseída",
        "un niño con una muñeca idéntica a él",
        "un sonámbulo que no recuerda nada",
        "un vecino que nunca se ve de día",
      ],
      criatura: [
        "un fantasma encadenado",
        "una sombra con forma humana",
        "un demonio de ojos rojos",
        "una criatura que se arrastra por las paredes",
        "un espantapájaros que se mueve",
        "una criatura sin rostro",
        "un payaso siniestro",
        "una aparición en el espejo",
      ],
      animal: [
        "un cuervo negro",
        "una rata gris",
        "un murciélago pequeño",
        "un gato negro",
        "un cuervo con un ala rota",
        "una serpiente en un frasco de formol",
        "un perro que aúlla sin razón",
        "una polilla gigante nocturna",
      ],
      objeto: [
        "una muñeca de porcelana agrietada",
        "un espejo antiguo",
        "una caja de música oxidada",
        "un diario con páginas arrancadas",
        "una vela que nunca se apaga",
        "una fotografía con una figura extra",
        "un teléfono antiguo que suena solo",
        "una llave que abre puertas que no existen",
      ],
      ropa: [
        "con un camisón manchado",
        "con una bata de hospital rasgada",
        "con un abrigo negro largo",
        "con un vestido de novia deshilachado",
        "con un vestido de época deshecho",
        "con una máscara de gas antigua",
        "con un traje de payaso descosido",
        "con vendas cubriendo todo el cuerpo",
      ],
      accesorio: [
        "con un collar con un relicario oxidado",
        "con guantes de cuero negro",
        "con un anillo con una piedra oscura",
        "con un antifaz de porcelana",
        "con un rosario roto",
        "con una llave oxidada colgando del cuello",
        "con un guante quirúrgico manchado",
        "con un parche en el ojo",
      ],
      atributo: [
        "con la piel pálida como la muerte",
        "con las manos cubiertas de sangre seca",
        "con una sonrisa que no debería existir",
        "con los ojos completamente negros",
        "con las venas negras visibles bajo la piel",
        "con la sombra que se mueve sola",
        "con una respiración que no coincide con su pecho",
        "con dedos anormalmente largos",
      ],
      habilidad: [
        "que puede aparecer y desaparecer sin aviso",
        "que susurra en idiomas desconocidos",
        "que controla a otros con la mirada",
        "que nunca duerme",
        "que puede predecir cómo morirá alguien",
        "que se refleja distinto en cada espejo",
        "que atrae a los insectos",
        "que no proyecta sombra",
      ],
      vehiculo: [
        "una ambulancia abandonada",
        "un tren fantasma detenido",
        "una carreta funeraria vieja",
        "un auto sin conductor",
        "un tren detenido en medio de la nada",
        "un elevador que baja solo",
        "una silla de ruedas vacía que se mueve",
        "un bote a la deriva",
      ],
      arma: [
        "con un cuchillo oxidado",
        "con un hacha manchada",
        "con unas tijeras enormes",
        "con una motosierra vieja",
        "con una jeringa vieja",
        "con una guadaña oxidada",
        "con un bisturí",
        "con una soga",
      ],
      planta: [
        "entre árboles secos y retorcidos",
        "rodeado de enredaderas muertas",
        "junto a flores negras marchitas",
        "entre raíces que sobresalen del suelo",
        "entre hongos venenosos",
        "junto a un árbol lleno de cuervos posados",
        "rodeado de zarzas que enredan los pies",
        "entre flores marchitas que huelen a descomposición",
      ],
      comida: [
        "sosteniendo una manzana podrida",
        "con un frasco de líquido oscuro",
        "sosteniendo un trozo de carne cruda",
        "con una taza de té frío olvidada",
        "sosteniendo un frasco con algo flotando dentro",
        "con un plato de carne que aún se mueve",
        "sosteniendo leche cortada",
        "con galletas mordidas por algo desconocido",
      ],
      lugar: [
        "dentro de una casa abandonada",
        "en un cementerio cubierto de niebla",
        "en un sótano oscuro y húmedo",
        "frente a un hospital psiquiátrico en ruinas",
        "dentro de un manicomio abandonado",
        "en un túnel del metro clausurado",
        "en el ático de una casa vieja",
        "dentro de una morgue vacía",
      ],
      clima: [
        "bajo una luna llena rojiza",
        "con niebla que no deja ver más allá de unos metros",
        "durante una tormenta eléctrica nocturna",
        "con un silencio antinatural en el aire",
        "con un frío que no tiene explicación",
        "bajo relámpagos sin trueno",
        "con una calma antes de una tormenta que nunca llega",
        "con el aire cargado de un olor a podredumbre",
      ],
      material: [
        "hecho de hueso",
        "hecho de madera podrida",
        "hecho de vidrio agrietado",
        "hecho de tela raída",
        "hecho de tela de araña",
        "hecho de piel curtida sin curar",
        "hecho de cristal roto",
        "hecho de cera derretida",
      ],
      accion: [
        "mientras camina arrastrando los pies",
        "mientras susurra algo inentendible",
        "mientras observa fijamente desde la ventana",
        "mientras escribe algo en las paredes",
        "mientras cuenta algo en voz baja hacia atrás",
        "mientras dibuja símbolos en el suelo",
        "mientras se mira las manos sin parpadear",
        "mientras golpea suavemente una puerta cerrada",
      ],
    },
  },
  {
    id: 'mitologia',
    name: 'Mitología',
    icon: 'assets/icons/cat-mitologia.svg',
    banks: {
      personaje: [
        "un oráculo griego",
        "una sacerdotisa egipcia",
        "un guerrero vikingo",
        "un faraón momificado",
        "un semidiós griego",
        "una valquiria",
        "un escriba egipcio",
        "un druida celta",
      ],
      criatura: [
        "un centauro",
        "una esfinge",
        "el lobo Fenrir",
        "un cancerbero de tres cabezas",
        "una hidra de siete cabezas",
        "un ave fénix",
        "el can Cerbero",
        "una nereida",
        "una medusa",
      ],
      animal: [
        "una serpiente del Nilo",
        "un águila dorada",
        "un toro sagrado",
        "un búho blanco",
        "un carnero dorado",
        "un chacal del desierto",
        "un lobo blanco nórdico",
        "un halcón de Horus",
      ],
      objeto: [
        "un cetro dorado",
        "una lira antigua",
        "un ánfora de barro",
        "una tablilla con jeroglíficos",
        "la lira de Orfeo",
        "un ojo de Horus tallado",
        "un cuerno de Thor",
        "un espejo de obsidiana azteca",
      ],
      ropa: [
        "con una toga blanca",
        "con una túnica egipcia bordada en oro",
        "con una armadura vikinga de cuero",
        "con un manto púrpura de emperador",
        "con una piel de león como capa",
        "con un peto de guerrero espartano",
        "con una túnica de sacerdote del Nilo",
        "con un manto de plumas de quetzal",
      ],
      accesorio: [
        "con un tocado con forma de serpiente",
        "con un brazalete de oro",
        "con una corona de olivo",
        "con un amuleto en forma de escarabajo",
        "con un ánkh colgando del cuello",
        "con un casco alado",
        "con un cinturón de fuerza divina",
        "con brazaletes de serpiente enroscada",
      ],
      atributo: [
        "con un rayo en la mano",
        "con alas en los talones",
        "con la cabeza de un chacal",
        "con ojos que ven el pasado y el futuro",
        "con un rayo dorado en la frente",
        "con plumas en lugar de cabello",
        "con ojos como el fuego eterno",
        "con la piel dorada como el sol",
      ],
      habilidad: [
        "que controla los rayos y truenos",
        "que puede transformarse en cualquier animal",
        "que guía las almas al inframundo",
        "que tiene fuerza para mover montañas",
        "que puede cambiar de forma a voluntad",
        "que gobierna las mareas",
        "que resucita de sus propias cenizas",
        "que ve a través del tiempo",
      ],
      vehiculo: [
        "un carro tirado por caballos",
        "una barca solar egipcia",
        "un barco vikingo con proa de dragón",
        "un carruaje dorado de los dioses",
        "la barca de Caronte",
        "un trineo tirado por cabras",
        "un carro alado",
        "una balsa funeraria egipcia",
      ],
      arma: [
        "con un tridente",
        "con un martillo de guerra",
        "con un arco de plata",
        "con una espada envuelta en fuego",
        "con el mjölnir",
        "con una espada de fuego celestial",
        "con un arco de Apolo",
        "con una lanza que nunca falla",
      ],
      planta: [
        "junto a un olivo sagrado",
        "entre juncos del Nilo",
        "rodeado de laureles",
        "cerca de un árbol de la vida dorado",
        "junto al loto sagrado del Nilo",
        "entre manzanas doradas de las Hespérides",
        "rodeado de cipreses del inframundo",
        "cerca de un roble sagrado nórdico",
      ],
      comida: [
        "sosteniendo una copa de néctar",
        "con un racimo de uvas",
        "sosteniendo pan y cerveza egipcia",
        "con una copa de hidromiel",
        "sosteniendo ambrosía de los dioses",
        "con un plato de higos y dátiles",
        "sosteniendo un cuerno de hidromiel eterno",
        "con pan de ofrenda sagrado",
      ],
      lugar: [
        "en la cima del monte Olimpo",
        "dentro de una pirámide egipcia",
        "en el gran salón de Valhalla",
        "junto a las orillas del río Nilo",
        "en las profundidades del inframundo",
        "junto al árbol Yggdrasil",
        "en el templo de Karnak",
        "en el laberinto del Minotauro",
      ],
      clima: [
        "bajo un cielo partido por rayos",
        "con arena levantada por el viento del desierto",
        "entre nubes doradas al amanecer",
        "bajo una aurora boreal",
        "bajo una tormenta enviada por los dioses",
        "con el desierto ardiendo bajo el sol de Ra",
        "entre nieblas del inframundo",
        "bajo el fuego de un volcán sagrado",
      ],
      material: [
        "hecho de oro puro",
        "hecho de mármol blanco",
        "hecho de bronce antiguo",
        "hecho de piedra caliza",
        "hecho de oricalco",
        "hecho de obsidiana pulida",
        "hecho de electro, oro y plata",
        "hecho de madera de cedro sagrado",
      ],
      accion: [
        "mientras lanza un rayo desde su mano",
        "mientras cruza el río de los muertos",
        "mientras narra una profecía",
        "mientras lucha contra un monstruo marino",
        "mientras forja un arma divina",
        "mientras conduce almas al más allá",
        "mientras desafía a los dioses",
        "mientras consulta un oráculo",
      ],
    },
  },
  {
    id: 'estudio',
    name: 'Estudio de dibujo',
    icon: 'assets/icons/cat-estudio.svg',
    banks: {
      personaje: [
        "una persona leyendo un libro",
        "un anciano sentado en un banco",
        "una estudiante escribiendo en un cuaderno",
        "un hombre esperando el bus",
        "una persona cocinando en la cocina",
        "un niño jugando con bloques",
        "una señora tejiendo en el sillón",
        "un ciclista deteniéndose en la esquina",
      ],
      criatura: [
        "un caracol de jardín",
        "una araña común",
        "una mariposa nocturna",
        "un escarabajo pequeño",
        "una hormiga cargando una hoja",
        "una libélula posada en una rama",
        "un gusano de seda",
        "un grillo entre el pasto",
      ],
      animal: [
        "un gato doméstico",
        "un perro labrador",
        "una paloma común",
        "un caballo de granja",
        "una vaca pastando",
        "un pato en un estanque",
        "un conejo doméstico",
        "una ardilla en un árbol",
      ],
      objeto: [
        "una taza de cerámica",
        "un libro de tapa dura",
        "una mochila escolar",
        "una cámara fotográfica",
        "un paraguas cerrado apoyado en una silla",
        "una regadera de metal",
        "un bolso de mano",
        "un termo de agua",
      ],
      ropa: [
        "con un suéter de lana",
        "con una chaqueta de mezclilla",
        "con un vestido de algodón",
        "con una camisa a cuadros",
        "con un delantal de cocina",
        "con botas de lluvia",
        "con una boina de artista",
        "con un overol de trabajo",
      ],
      accesorio: [
        "con lentes de lectura",
        "con un reloj de pulsera simple",
        "con una bufanda de lana",
        "con aros pequeños",
        "con una cinta métrica al cuello",
        "con un delantal con bolsillos",
        "con un pañuelo en la cabeza",
        "con guantes de jardinería",
      ],
      atributo: [
        "con el pelo canoso",
        "con una expresión pensativa",
        "con arrugas alrededor de los ojos",
        "con una postura encorvada",
        "con las manos llenas de harina",
        "con el pelo recogido en un moño",
        "con manchas de pintura en la ropa",
        "con los brazos cruzados pensando",
      ],
      habilidad: [
        "que toca el piano con destreza",
        "que dibuja con mucho detalle",
        "que cocina platos elaborados",
        "que teje a mano con rapidez",
        "que arregla cosas con las manos",
        "que hornea pan todos los domingos",
        "que cuida un huerto con dedicación",
        "que repara bicicletas como hobby",
      ],
      vehiculo: [
        "una bicicleta común",
        "un auto familiar",
        "un autobús urbano",
        "una patineta simple",
        "un tren de carga pasando",
        "una camioneta de reparto",
        "un tranvía urbano",
        "un monopatín apoyado en la pared",
      ],
      arma: [
        "con un martillo en la mano",
        "con unas tijeras de jardinería",
        "con un cuchillo de cocina",
        "con un destornillador",
        "con unas pinzas de cocina",
        "con un rastrillo de jardín",
        "con una pala pequeña",
        "con un cepillo de limpieza",
      ],
      planta: [
        "junto a una maceta de geranios",
        "entre árboles de un parque",
        "cerca de un jardín de hierbas",
        "con un florero de girasoles en la mesa",
        "junto a un huerto de tomates",
        "entre macetas de albahaca y menta",
        "cerca de un limonero en el patio",
        "con enredaderas subiendo por una reja",
      ],
      comida: [
        "sosteniendo una taza de café",
        "comiendo una tostada con mermelada",
        "con un plato de fruta fresca",
        "sosteniendo un vaso de jugo de naranja",
        "sosteniendo un pan recién horneado",
        "con una ensalada fresca en un bowl",
        "comiendo sopa casera",
        "sosteniendo un vaso de limonada",
      ],
      lugar: [
        "en un parque tranquilo",
        "dentro de una cafetería con ventanas grandes",
        "en la sala de una casa",
        "en una biblioteca silenciosa",
        "en un mercado de frutas y verduras",
        "en el patio trasero de una casa",
        "en una lavandería de barrio",
        "en un taller de carpintería",
      ],
      clima: [
        "en una tarde soleada",
        "bajo una llovizna suave",
        "en una mañana con niebla ligera",
        "en un día nublado de otoño",
        "en una tarde de primavera templada",
        "bajo el sol de mediodía",
        "en una noche fresca de verano",
        "con brisa suave de otoño",
      ],
      material: [
        "hecho de madera pulida",
        "hecho de cerámica pintada",
        "hecho de tela de algodón",
        "hecho de vidrio soplado",
        "hecho de bambú",
        "hecho de lana tejida a mano",
        "hecho de arcilla",
        "hecho de metal reciclado",
      ],
      accion: [
        "mientras toma una taza de té",
        "mientras escribe en su diario",
        "mientras riega las plantas",
        "mientras camina con su perro",
        "mientras amasa pan en la cocina",
        "mientras dobla ropa recién lavada",
        "mientras arregla una bicicleta",
        "mientras pinta una pared",
      ],
    },
  }
];

// Frases genéricas sin carga temática: se suman siempre al pool disponible
// sin importar qué categoría(s) elija el usuario (ver buildPool en app.js).
// No incluye "criatura": ese slot siempre es específico de cada categoría.
const WTD_TRANSVERSAL_BANKS = {
  personaje: [
        "un niño curioso",
        "un anciano sabio",
        "una mujer decidida",
        "un joven distraído",
        "una persona sonriente",
        "un trabajador cansado",
      ],
  animal: [
        "un perro",
        "un gato",
        "un caballo",
        "un conejo",
        "una vaca",
        "un cerdo",
        "una oveja",
        "un pato",
        "un ratón",
        "una tortuga",
      ],
  objeto: [
        "una mochila",
        "un libro",
        "una caja",
        "una lámpara",
        "un reloj",
        "una maleta",
        "un paraguas",
        "una cámara",
      ],
  ropa: [
        "con una camisa",
        "con un abrigo",
        "con un sombrero",
        "con una bufanda",
        "con pantalones cómodos",
        "con un vestido simple",
        "con una chaqueta",
        "con zapatillas deportivas",
      ],
  accesorio: [
        "con lentes",
        "con un reloj de pulsera",
        "con una mochila cruzada",
        "con un collar sencillo",
        "con aretes pequeños",
        "con una pulsera",
        "con un cinturón",
        "con una gorra",
      ],
  atributo: [
        "con el pelo largo",
        "con una sonrisa amplia",
        "con los ojos cerrados",
        "con una postura relajada",
        "con manos grandes",
        "con una mirada seria",
        "con pecas en la cara",
        "con el ceño fruncido",
      ],
  habilidad: [
        "que aprende rápido",
        "que es muy paciente",
        "que tiene buena memoria",
        "que es curioso por naturaleza",
      ],
  vehiculo: [
        "una bicicleta",
        "un auto",
        "un camión",
        "un bote pequeño",
        "una moto",
        "un tren",
        "un avión",
        "una carreta",
      ],
  arma: [
        "con un cuchillo",
        "con un bastón",
        "con una honda",
        "con un palo largo",
        "con una piedra en la mano",
        "con un látigo",
      ],
  planta: [
        "junto a un árbol",
        "entre pasto alto",
        "cerca de flores silvestres",
        "rodeado de arbustos",
        "junto a un jardín",
        "entre hojas caídas",
        "cerca de un campo de trigo",
        "junto a una enredadera",
      ],
  comida: [
        "sosteniendo una manzana",
        "con una taza de agua",
        "comiendo pan",
        "sosteniendo una naranja",
        "con un vaso de leche",
        "comiendo una galleta",
        "sosteniendo un plátano",
        "con un plato de arroz",
        "sosteniendo una zanahoria",
        "con un puñado de nueces",
      ],
  lugar: [
        "en un camino de tierra",
        "junto a un río",
        "en una plaza",
        "frente a una casa",
        "en la cima de una colina",
        "dentro de un mercado",
        "en una calle vacía",
        "junto a un lago",
      ],
  clima: [
        "bajo el sol",
        "con lluvia ligera",
        "en un día nublado",
        "con viento fuerte",
        "en una noche estrellada",
        "con niebla",
        "en un día caluroso",
        "con frío intenso",
        "bajo la luna llena",
        "con una brisa suave",
      ],
  material: [
        "hecho de madera",
        "hecho de metal",
        "hecho de vidrio",
        "hecho de tela",
        "hecho de piedra",
        "hecho de plástico",
        "hecho de cuero",
        "hecho de papel",
        "hecho de cerámica",
        "hecho de goma",
      ],
  accion: [
        "mientras camina",
        "mientras descansa",
        "mientras observa el horizonte",
        "mientras conversa",
        "mientras trabaja",
        "mientras piensa",
        "mientras sonríe",
        "mientras espera",
        "mientras corre",
        "mientras duerme",
        "mientras toma una taza de té",
        "mientras juega tenis",
        "mientras juega ajedrez",
        "mientras se pinta las uñas",
        "mientras teje una bufanda",
        "mientras toca la guitarra",
        "mientras baila",
        "mientras hace yoga",
        "mientras lee el periódico",
        "mientras dispara con un arco",
        "mientras anda en patineta",
        "mientras toma una siesta en un sillón",
      ],
};
