// Definición de slots ("blanks") disponibles para armar un prompt.
// kind: 'subject' -> puede ser el sujeto de la frase (se usa capitalizado tal cual, sin conector)
//                     o, si no es el sujeto elegido, se antepone `connector`.
//       'clause'  -> siempre se agrega como cláusula tras una coma.
const WTD_SLOTS = [
  { id: 'personaje', label: 'Personaje', icon: 'assets/icons/el-personaje.svg', kind: 'subject', connector: 'junto a' },
  { id: 'criatura',  label: 'Criatura',  icon: 'assets/icons/el-criatura.svg',  kind: 'subject', connector: 'junto a' },
  { id: 'animal',    label: 'Animal',    icon: 'assets/icons/el-animal.svg',    kind: 'subject', connector: 'acompañado de' },
  { id: 'objeto',    label: 'Objeto',    icon: 'assets/icons/el-objeto.svg',    kind: 'subject', connector: 'cargando' },
  { id: 'ropa',      label: 'Ropa',      icon: 'assets/icons/el-ropa.svg',      kind: 'clause' },
  { id: 'accesorio', label: 'Accesorio', icon: 'assets/icons/el-accesorio.svg', kind: 'clause' },
  { id: 'atributo',  label: 'Atributo',  icon: 'assets/icons/el-atributo.svg',  kind: 'clause' },
  { id: 'habilidad', label: 'Habilidad', icon: 'assets/icons/el-habilidad.svg', kind: 'clause' },
  { id: 'vehiculo',  label: 'Vehículo',  icon: 'assets/icons/el-vehiculo.svg',  kind: 'subject', connector: 'sobre' },
  { id: 'arma',      label: 'Arma',      icon: 'assets/icons/el-arma.svg',      kind: 'clause' },
  { id: 'planta',    label: 'Planta',    icon: 'assets/icons/el-planta.svg',    kind: 'clause' },
  { id: 'comida',    label: 'Comida',    icon: 'assets/icons/el-comida.svg',    kind: 'clause' },
  { id: 'lugar',     label: 'Lugar',     icon: 'assets/icons/el-lugar.svg',     kind: 'clause' },
  { id: 'clima',     label: 'Clima',     icon: 'assets/icons/el-clima.svg',     kind: 'clause' },
  { id: 'material',  label: 'Material',  icon: 'assets/icons/el-material.svg', kind: 'clause' },
  { id: 'accion',    label: 'Acción',    icon: 'assets/icons/el-accion.svg',   kind: 'clause' },
];

// Orden de prioridad para elegir el sujeto de la frase.
const WTD_SUBJECT_PRIORITY = ['personaje', 'criatura', 'animal', 'vehiculo', 'objeto'];

// Sujetos genéricos de respaldo, por si el usuario no elige ningún slot tipo "subject".
const WTD_FALLBACK_SUBJECTS = ['Algo inesperado', 'Una escena curiosa', 'Alguien de otro mundo'];

const WTD_CATEGORIES = [
  {
    id: 'fantasia',
    name: 'Fantasía medieval',
    icon: 'assets/icons/cat-fantasia.svg',
    banks: {
      personaje: [
        'un caballero errante con la armadura abollada',
        'una hechicera exiliada del reino del norte',
        'un enano herrero que forjó su propia espada',
        'una princesa que escapó de su propia boda',
      ],
      criatura: [
        'un dragón anciano de escamas doradas',
        'un grifo que custodia una torre olvidada',
        'una hidra de tres cabezas dormida en el pantano',
        'un espíritu del bosque hecho de raíces y musgo',
      ],
      animal: [
        'un lobo blanco con ojos color ámbar',
        'un caballo negro que nunca se cansa',
        'un cuervo que habla en acertijos',
        'un zorro con una cola hecha de fuego frío',
      ],
      vehiculo: [
        'una carroza tirada por caballos fantasmales',
        'un barco vikingo varado en tierra firme',
        'una alfombra voladora tejida con hilos de plata',
        'un carruaje real sin cochero',
      ],
      objeto: [
        'un grimorio sellado con cadenas de hierro',
        'una corona maldita que nadie se atreve a usar',
        'un cofre del tesoro que canta al abrirse',
        'una lámpara con un genio dormido dentro',
      ],
      atributo: [
        'con una cicatriz en forma de estrella',
        'con una mirada que revela mil batallas',
        'con una sonrisa que oculta un secreto real',
        'con el cabello trenzado con hojas doradas',
      ],
      ropa: [
        'vistiendo una capa remendada mil veces',
        'con una armadura grabada con runas antiguas',
        'envuelto en una túnica de mago itinerante',
        'con botas de cuero gastadas por el camino',
      ],
      accesorio: [
        'con un amuleto que brilla cerca del peligro',
        'usando un anillo grabado con un nombre olvidado',
        'con una capucha bordada con hilo de plata',
        'cargando un talismán tallado en hueso de dragón',
      ],
      arma: [
        'empuñando una espada que canta antes de la batalla',
        'con un arco tallado en madera de roble sagrado',
        'sosteniendo un hacha con el filo mellado',
        'con un báculo rematado por un cristal palpitante',
      ],
      habilidad: [
        'capaz de hablar con los animales del bosque',
        'con el poder de curar heridas con un cántico',
        'capaz de leer el destino en las estrellas',
        'con la habilidad de invocar una tormenta de hielo',
      ],
      material: [
        'forjado en un metal que nunca se oxida',
        'hecho de piedra de una torre derrumbada',
        'tallado en el colmillo de una bestia legendaria',
        'cubierto de escamas de dragón cosidas a mano',
      ],
      lugar: [
        'frente a un castillo devorado por la hiedra',
        'en las ruinas de un templo olvidado',
        'cerca de un lago donde nadie se atreve a nadar',
        'dentro de una mazmorra iluminada por hongos brillantes',
      ],
      clima: [
        'bajo una luna teñida de rojo sangre',
        'durante una tormenta que huele a azufre',
        'en medio de una niebla que susurra nombres',
        'bajo una lluvia de cenizas de un volcán lejano',
      ],
      accion: [
        'mientras huye de un ejército de esqueletos',
        'justo antes de romper un sello ancestral',
        'mientras negocia con un demonio menor',
        'mientras cruza un puente que se desmorona',
      ],
      planta: [
        'rodeado de flores que se cierran al anochecer',
        'entre árboles que susurran advertencias',
        'junto a una enredadera con espinas de cristal',
        'sobre un campo de trigo negro',
      ],
      comida: [
        'comiendo un pan que nunca se termina',
        'bebiendo una poción que sabe a tormenta',
        'compartiendo una fruta prohibida por el rey',
        'masticando una raíz que da visiones',
      ],
    },
  },
  {
    id: 'editorial',
    name: 'Editorial y cartoon',
    icon: 'assets/icons/cat-editorial.svg',
    banks: {
      personaje: [
        'un panda que trabaja como repartidor de pizza',
        'una abuela que compite en carreras de patinetas',
        'un oficinista con superpoderes que nunca usa',
        'una niña que colecciona monstruos en frascos',
      ],
      criatura: [
        'una nube con cara que sigue a todos lados',
        'un monstruo peludo que solo quiere un abrazo',
        'un fantasma que trabaja de guardia de seguridad',
        'una mascota imaginaria que se volvió real por error',
      ],
      animal: [
        'un gato que insiste en manejar el auto',
        'un pato con lentes de sol todo el año',
        'una tortuga que participa en carreras de bicicleta',
        'un perro salchicha disfrazado de superhéroe',
      ],
      vehiculo: [
        'una bicicleta con una canasta llena de globos',
        'un carrito de helados que también vuela',
        'un patín eléctrico que se queda sin batería siempre',
        'una camioneta de mudanzas pintada como arcoíris',
      ],
      objeto: [
        'un paraguas que predice el clima mal siempre',
        'una lonchera con un candado imposible de abrir',
        'un control remoto que cambia canales de otra dimensión',
        'una taza que nunca se queda vacía de café',
      ],
      atributo: [
        'con un peinado que desafía la gravedad',
        'con una sonrisa que ilumina la cuadra entera',
        'con calcetines que nunca combinan',
        'con las mejillas siempre sonrojadas de vergüenza',
      ],
      ropa: [
        'vistiendo un pijama de dinosaurio en pleno día',
        'con una bufanda tres veces más larga que su cuerpo',
        'usando un delantal lleno de manchas de pintura',
        'con zapatos que hacen ruido de pato al caminar',
      ],
      accesorio: [
        'con una mochila que pesa más que él mismo',
        'usando lentes de sol en forma de estrella',
        "con un botón que dice 'pregúntame por mi gato'",
        'cargando un termo decorado con calcomanías',
      ],
      arma: [
        'empuñando una espátula como si fuera una espada',
        'con una pistola de agua recargada con jugo',
        'sosteniendo un globo aterrador con forma de espada',
        'con un rollo de papel higiénico como arma secreta',
      ],
      habilidad: [
        'capaz de encontrar estacionamiento en cualquier lugar',
        'con el don de hacer reír a cualquiera en tres segundos',
        'capaz de comer pizza sin ensuciarse nunca',
        'con la habilidad de dormir en cualquier posición',
      ],
      material: [
        'hecho completamente de gomitas de colores',
        'cubierto de pegatinas de todos los tamaños',
        'tejido con lana que huele a galletas',
        'construido con piezas de un juego de mesa viejo',
      ],
      lugar: [
        'en la fila del supermercado un sábado por la mañana',
        'dentro de una feria con demasiados juegos mecánicos',
        'en la sala de espera de un dentista muy colorido',
        'sobre el techo de una casa durante una fiesta de barrio',
      ],
      clima: [
        'bajo una llovizna que huele a pasto recién cortado',
        'durante un día tan soleado que los helados se derriten al instante',
        'en medio de una ventisca de confeti de una fiesta',
        'bajo un arcoíris doble después de la lluvia',
      ],
      accion: [
        'mientras intenta no reírse en una reunión aburrida',
        'justo cuando se le cae el helado por segunda vez',
        'mientras baila sin que nadie lo note',
        'mientras busca sus llaves durante quince minutos',
      ],
      planta: [
        'rodeado de girasoles más altos que él',
        'junto a un cactus que insiste en decorar con moños',
        'entre macetas pintadas por niños del vecindario',
        'cerca de un árbol con una casita de pájaros torcida',
      ],
      comida: [
        'comiendo un sándwich con demasiada mayonesa',
        'compartiendo una pizza con piña, para disgusto de todos',
        'bebiendo un batido que se derrama constantemente',
        'masticando palomitas mientras se le caen todas al suelo',
      ],
    },
  },
  {
    id: 'cienciaficcion',
    name: 'Ciencia Ficción',
    icon: 'assets/icons/cat-cienciaficcion.svg',
    banks: {
      personaje: [
        'un hacker con un ojo cibernético parpadeante',
        'una piloto espacial que perdió su nave tres veces',
        'un androide que cree que sueña',
        'una mercenaria con el brazo reemplazado por metal',
      ],
      criatura: [
        'un alien con piel translúcida y luces internas',
        'una IA que escapó de su servidor',
        'un enjambre de nanobots con forma de animal',
        'una criatura mutante que vive en los ductos de la estación',
      ],
      animal: [
        'un gato con un chip implantado en la oreja',
        'un perro robótico con las patas oxidadas',
        'un halcón con alas de metal plegable',
        'una serpiente cibernética que roba datos',
      ],
      vehiculo: [
        'una moto que flota sobre un río de neón',
        'una nave destartalada que escupe humo morado',
        'un tren bala que atraviesa rascacielos',
        'una cápsula de escape sin combustible',
      ],
      objeto: [
        'un disco duro con la última copia de un recuerdo',
        'una pistola de plasma con la batería al mínimo',
        'un holograma roto de una ciudad que ya no existe',
        'un chip pirateado directo del gobierno',
      ],
      atributo: [
        'con un tatuaje que brilla bajo luz ultravioleta',
        'con los ojos reemplazados por cámaras rojas',
        'con una sonrisa hecha de dientes metálicos',
        'con cicatrices de una cirugía cibernética barata',
      ],
      ropa: [
        'con una chaqueta llena de cables sueltos',
        'vistiendo un traje espacial remendado con cinta',
        'con botas magnéticas gastadas',
        'envuelto en un poncho reflectante anti-dron',
      ],
      accesorio: [
        'con lentes de realidad aumentada rotos',
        'usando audífonos que traducen cualquier idioma',
        'con un brazalete que rastrea su ubicación',
        'cargando una tarjeta de acceso robada',
      ],
      arma: [
        'empuñando un rifle de energía improvisado',
        'con un cuchillo vibratorio hecho en casa',
        'sosteniendo un lanzagranadas de plasma',
        'con guantes eléctricos capaces de freír un panel',
      ],
      habilidad: [
        'capaz de hackear cualquier sistema en segundos',
        'con el don de pilotar naves sin manual',
        'capaz de falsificar cualquier identidad digital',
        'con reflejos mejorados quirúrgicamente',
      ],
      material: [
        'hecho de aleación reciclada de una nave caída',
        'cubierto de placas de titanio abolladas',
        'construido con piezas de tres androides distintos',
        'revestido en un plástico que cambia de color',
      ],
      lugar: [
        'en un mercado negro flotante sobre la ciudad',
        'dentro de una estación espacial abandonada',
        'en un callejón iluminado solo por anuncios holográficos',
        'sobre una luna colonizada a medias',
      ],
      clima: [
        'bajo una lluvia ácida que oxida el metal',
        'durante un apagón que deja la ciudad a oscuras',
        'en medio de una tormenta de radiación solar',
        'bajo el resplandor de dos soles artificiales',
      ],
      accion: [
        'mientras escapa de drones de seguridad',
        'justo cuando la nave pierde el oxígeno',
        'mientras borra su rastro de la red',
        'mientras negocia con un cártel interestelar',
      ],
      planta: [
        'junto a un jardín hidropónico con luces moradas',
        'rodeado de algas bioluminiscentes en tanques rotos',
        'entre plantas mutantes que crecen en la basura espacial',
        'cerca de un árbol sintético que nunca florece',
      ],
      comida: [
        'comiendo una barra nutricional caducada',
        'bebiendo un café sintético con sabor a metal',
        'compartiendo comida enlatada de otra galaxia',
        "masticando algo que la máquina llamó 'pizza'",
      ],
    },
  },
  {
    id: 'terror',
    name: 'Terror y misterio',
    icon: 'assets/icons/cat-terror.svg',
    banks: {
      personaje: [
        'un sobreviviente con la ropa hecha jirones',
        'una niña que ya no proyecta sombra',
        'un cazador de monstruos con más cicatrices que victorias',
        'un vigilante nocturno que dejó de dormir hace semanas',
      ],
      criatura: [
        'una criatura sin rostro que imita voces',
        'un ser que solo se mueve cuando nadie mira',
        'una sombra con demasiados dientes',
        'algo que vive debajo de las escaleras del sótano',
      ],
      animal: [
        'un perro con los ojos completamente blancos',
        'un cuervo que repite la última palabra que escuchó',
        'un gato que llegó antes que la casa existiera',
        'un ciervo con astas hechas de huesos humanos',
      ],
      vehiculo: [
        'una furgoneta abandonada con el motor aún caliente',
        'un tren fantasma que nunca llega a la estación',
        'un bote a la deriva sin remos',
        'un auto que arranca solo a medianoche',
      ],
      objeto: [
        'una muñeca con la cabeza girada al revés',
        'un espejo que refleja un cuarto distinto',
        'una caja de música que toca sola de noche',
        'un diario con páginas escritas después de su muerte',
      ],
      atributo: [
        'con una sonrisa que no llega a los ojos',
        'con la piel fría al tacto aunque respire',
        'con una voz que suena a varias personas a la vez',
        'con las manos temblando sin razón aparente',
      ],
      ropa: [
        'con un vestido manchado que nunca se seca',
        'vistiendo un abrigo tres tallas más grande',
        'con una máscara que ya no se puede quitar',
        'envuelto en vendas que huelen a humedad',
      ],
      accesorio: [
        'con un collar que se aprieta solo',
        'usando lentes que muestran algo distinto en cada reflejo',
        'con un anillo que deja marcas de quemadura',
        'cargando una llave que abre una puerta que no existe',
      ],
      arma: [
        'sosteniendo un cuchillo oxidado que encontró en la pared',
        'con un hacha clavada en un tronco que sangra',
        'empuñando una linterna que parpadea cada vez más',
        'con unas tijeras que aparecen en su bolsillo sin explicación',
      ],
      habilidad: [
        'capaz de escuchar conversaciones de hace décadas',
        'con el don de encontrar puertas que no deberían existir',
        'capaz de saber cuándo alguien va a morir',
        'con la habilidad de no dejar huellas al caminar',
      ],
      material: [
        'cubierto de un moho que se mueve despacio',
        'hecho de madera que gotea algo oscuro',
        'tallado en hueso pulido hasta brillar',
        'envuelto en tela que absorbe la luz',
      ],
      lugar: [
        'en un pasillo de hospital abandonado',
        'dentro de una casa que cambia de forma de noche',
        'en un sótano donde el aire se siente pesado',
        'cerca de un pozo del que sale un canto suave',
      ],
      clima: [
        'bajo una niebla que apaga cualquier sonido',
        'durante un apagón que dura toda la noche',
        'en medio de una lluvia que no moja',
        'bajo un cielo sin estrellas ni luna',
      ],
      accion: [
        'mientras cuenta los pasos detrás suyo',
        'justo cuando las luces empiezan a parpadear',
        'mientras evita mirar directamente al espejo',
        'mientras algo respira del otro lado de la puerta',
      ],
      planta: [
        'rodeado de árboles secos que crujen sin viento',
        'junto a flores negras que solo crecen de noche',
        'entre raíces que sobresalen del suelo del cementerio',
        'cerca de un jardín que nadie ha podado en años',
      ],
      comida: [
        'comiendo algo que ya no recuerda haber cocinado',
        'bebiendo agua de un vaso que nunca se vacía',
        'encontrando comida fresca en una casa vacía',
        'masticando algo con un sabor a metal y tierra',
      ],
    },
  },
  {
    id: 'mitologia',
    name: 'Mitología',
    icon: 'assets/icons/cat-mitologia.svg',
    banks: {
      personaje: [
        'un héroe que desafió a los dioses por amor',
        'una sacerdotisa que interpreta los designios del oráculo',
        'un rey que negoció su destino con la Parca',
        'una guerrera bendecida por un dios olvidado',
      ],
      criatura: [
        'una esfinge que solo habla en acertijos',
        'un cancerbero de tres cabezas custodiando el inframundo',
        'una serpiente marina que rodea el mundo entero',
        'un ave de fuego que renace de sus propias cenizas',
      ],
      animal: [
        'un lobo gigante que amenaza con devorar el sol',
        'un caballo alado que nunca toca el suelo',
        'un toro sagrado con cuernos de oro',
        'una lechuza que acompaña a la diosa de la sabiduría',
      ],
      vehiculo: [
        'un carro tirado por caballos de fuego',
        'una barca que cruza el río de los muertos',
        'un carruaje del sol que recorre el cielo cada día',
        'una nave que navega entre las estrellas de los dioses',
      ],
      objeto: [
        'un rayo forjado por un herrero divino',
        'una copa que nunca se vacía de ambrosía',
        'una lira capaz de calmar a las bestias más feroces',
        'un báculo con el poder de abrir el inframundo',
      ],
      atributo: [
        'con ojos que brillan como el oro del Olimpo',
        'con una fuerza capaz de mover montañas',
        'con una belleza que enloquece a mortales y dioses',
        'con una voz que se escucha desde cualquier templo',
      ],
      ropa: [
        'vistiendo una túnica tejida por las musas',
        'con una armadura forjada en el corazón de un volcán',
        'envuelto en una capa hecha de estrellas',
        'con sandalias aladas que nunca tocan el polvo',
      ],
      accesorio: [
        'con una corona de laureles que nunca se marchita',
        'usando un amuleto grabado con símbolos olvidados',
        'con un brazalete que otorga la inmortalidad temporal',
        'cargando un cuerno que anuncia el fin de una era',
      ],
      arma: [
        'empuñando un tridente que agita los mares',
        'con una espada forjada con un rayo',
        'sosteniendo un arco que nunca falla su objetivo',
        'con un escudo capaz de reflejar cualquier maldición',
      ],
      habilidad: [
        'capaz de cambiar de forma a voluntad',
        'con el poder de controlar las tormentas',
        'capaz de ver el destino de cualquier mortal',
        'con la habilidad de hablar con los muertos',
      ],
      material: [
        'forjado en oro que jamás pierde su brillo',
        'tallado en mármol traído del monte sagrado',
        'hecho de nubes petrificadas por un hechizo',
        'cubierto de escamas de una bestia marina legendaria',
      ],
      lugar: [
        'en la cima de una montaña donde habitan los dioses',
        'frente a las puertas del inframundo',
        'dentro de un templo tallado en piedra blanca',
        'junto a un río cuyas aguas conceden el olvido',
      ],
      clima: [
        'bajo un cielo partido por un rayo divino',
        'en medio de una tormenta invocada por un dios furioso',
        'con una luz dorada que solo aparece en los templos',
        'durante un eclipse que los mortales temen',
      ],
      accion: [
        'mientras desafía a un dios a un duelo de voluntades',
        'justo antes de robar fuego para dárselo a los mortales',
        'mientras negocia con la Muerte misma',
        'mientras cumple la última de sus doce pruebas',
      ],
      planta: [
        'junto a un árbol que da frutos de oro',
        'rodeado de laureles sagrados que nadie corta',
        'entre flores que nacieron de la sangre de un héroe',
        'cerca de una vid que crece más rápido de lo normal',
      ],
      comida: [
        'comiendo ambrosía reservada solo para los dioses',
        'bebiendo néctar que otorga la eterna juventud',
        'compartiendo una granada que decide su destino',
        'probando un vino que nunca se termina en la copa',
      ],
    },
  },
  {
    id: 'estudio',
    name: 'Estudio de dibujo',
    icon: 'assets/icons/cat-estudio.svg',
    banks: {
      personaje: [
        'una persona esperando el autobús revisando el celular',
        'un repartidor cargando una pila de cajas',
        'una señora regando las plantas del balcón',
        'un estudiante quedándose dormido sobre sus apuntes',
      ],
      criatura: [
        'una araña tejiendo su tela en una esquina',
        'una polilla revoloteando cerca de la lámpara',
        'un caracol cruzando lentamente la vereda',
        'una lagartija tomando sol sobre una piedra',
      ],
      animal: [
        'un perro callejero durmiendo bajo un auto',
        'un gato estirándose sobre el respaldo del sofá',
        'una paloma picoteando migas en la plaza',
        'una ardilla enterrando una nuez en el parque',
      ],
      vehiculo: [
        'una bicicleta apoyada contra un poste',
        'un auto viejo estacionado en doble fila',
        'un carrito de supermercado con una rueda floja',
        'un scooter eléctrico tirado en la vereda',
      ],
      objeto: [
        'una taza de café ya fría a medio terminar',
        'una mochila abierta con los cuadernos asomando',
        'un paraguas roto olvidado en un rincón',
        'una caja de mudanza mal cerrada',
      ],
      atributo: [
        'con los hombros caídos por el cansancio',
        'con el pelo despeinado por el viento',
        'con las manos metidas en los bolsillos',
        'con la mirada perdida en el horizonte',
      ],
      ropa: [
        'con una chaqueta que le queda grande',
        'vistiendo el mismo suéter de siempre',
        'con las mangas de la camisa remangadas',
        'con zapatillas gastadas en la punta',
      ],
      accesorio: [
        'con audífonos puestos aunque no suene nada',
        'con lentes empañados por el frío',
        'con una bufanda enredada sin cuidado',
        'con un reloj que se le resbala de la muñeca',
      ],
      arma: [
        'sosteniendo un destornillador a medio usar',
        'con unas tijeras de cocina en la mano',
        'empuñando un rastrillo de jardín',
        'con un martillo colgando del cinturón',
      ],
      habilidad: [
        'capaz de estacionar en paralelo al primer intento',
        'con la costumbre de tararear mientras trabaja',
        'capaz de dormir sentado en cualquier transporte',
        'con el hábito de doblar servilletas sin darse cuenta',
      ],
      material: [
        'hecho de una tela desgastada por el uso',
        'cubierto de polvo después de la mudanza',
        'hecho de cartón reforzado con cinta',
        'salpicado de pintura de un proyecto anterior',
      ],
      lugar: [
        'en la parada de autobús bajo la marquesina',
        'dentro de una cafetería casi vacía',
        'en el pasillo de un supermercado a media tarde',
        'sentado en las escaleras de la entrada',
      ],
      clima: [
        'bajo un sol de mediodía sin sombra cerca',
        'durante una llovizna ligera que nadie esperaba',
        'con un viento que le vuela los papeles',
        'en una tarde nublada y gris',
      ],
      accion: [
        'mientras espera que cambie el semáforo',
        'justo al agacharse a atarse los cordones',
        'mientras carga las bolsas del mercado',
        'mientras revisa la hora en su reloj',
      ],
      planta: [
        'junto a una maceta con una planta medio marchita',
        'bajo un árbol que da poca sombra',
        'cerca de un jardín descuidado hace semanas',
        'entre el pasto recién cortado de la plaza',
      ],
      comida: [
        'comiendo un sándwich a medio camino',
        'bebiendo café de un termo abollado',
        'con una bolsa de papas fritas a medio abrir',
        'compartiendo una fruta con alguien más',
      ],
    },
  },
];
