// Definición de slots ("blanks") disponibles para armar un prompt.
// kind: 'subject' -> puede ser el sujeto de la frase (se usa capitalizado tal cual, sin conector)
//                     o, si no es el sujeto elegido, se antepone `connector`.
//       'clause'  -> siempre se agrega como cláusula tras una coma.
const WTD_SLOTS = [
  { id: 'personaje', label: 'Personaje', icon: 'assets/icons/el-personaje.svg', kind: 'subject', connector: 'junto a' },
  { id: 'criatura',  label: 'Criatura',  icon: 'assets/icons/el-criatura.svg',  kind: 'subject', connector: 'junto a' },
  { id: 'animal',    label: 'Animal',    icon: 'assets/icons/el-animal.svg',    kind: 'subject', connector: 'acompañado de' },
  { id: 'objeto',    label: 'Objeto',    icon: 'assets/icons/el-objeto.svg',    kind: 'subject', connector: 'cargando' },
  { id: 'ropa',      label: 'Ropa',      icon: 'assets/icons/el-ropa.svg',      kind: 'clause' },
  { id: 'accesorio', label: 'Accesorio', icon: 'assets/icons/el-accesorio.svg', kind: 'clause' },
  { id: 'atributo',  label: 'Atributo',  icon: 'assets/icons/el-atributo.svg',  kind: 'clause' },
  { id: 'habilidad', label: 'Habilidad', icon: 'assets/icons/el-habilidad.svg', kind: 'clause' },
  { id: 'vehiculo',  label: 'Vehículo',  icon: 'assets/icons/el-vehiculo.svg',  kind: 'subject', connector: 'sobre' },
  { id: 'arma',      label: 'Arma',      icon: 'assets/icons/el-arma.svg',      kind: 'clause' },
  { id: 'planta',    label: 'Planta',    icon: 'assets/icons/el-planta.svg',    kind: 'clause' },
  { id: 'comida',    label: 'Comida',    icon: 'assets/icons/el-comida.svg',    kind: 'clause' },
  { id: 'lugar',     label: 'Lugar',     icon: 'assets/icons/el-lugar.svg',     kind: 'clause' },
  { id: 'clima',     label: 'Clima',     icon: 'assets/icons/el-clima.svg',     kind: 'clause' },
  { id: 'material',  label: 'Material',  icon: 'assets/icons/el-material.svg', kind: 'clause' },
  { id: 'accion',    label: 'Acción',    icon: 'assets/icons/el-accion.svg',   kind: 'clause' },
];

// Orden de prioridad para elegir el sujeto principal de la frase.
const WTD_SUBJECT_PRIORITY = ['personaje', 'criatura', 'animal', 'vehiculo', 'objeto'];

// Sujeto genérico de respaldo, si el usuario no elige ningún slot tipo "subject".
const WTD_FALLBACK_SUBJECTS = ['Una escena'];

const WTD_CATEGORIES = [
  {
    id: 'fantasia',
    name: 'Fantasía medieval',
    icon: 'assets/icons/cat-fantasia.svg',
    banks: {
      personaje: [
        'un caballero errante',
        'una hechicera del bosque',
        'un herrero real',
        'un juglar itinerante',
      ],
      criatura: [
        'un dragón anciano',
        'un ogro de las montañas',
        'una arpía de alas doradas',
        'un trasgo de las cuevas',
      ],
      animal: [
        'un caballo blanco',
        'un halcón peregrino',
        'un lobo gris',
        'un cuervo negro',
      ],
      objeto: [
        'un pergamino enrollado',
        'una llave de bronce',
        'un cofre pequeño',
        'un candelabro de hierro',
      ],
      ropa: [
        'con una capa raída',
        'con una túnica de terciopelo',
        'con una armadura oxidada',
        'con un manto bordado',
      ],
      accesorio: [
        'con un amuleto de piedra',
        'con un anillo de sello',
        'con una corona de laurel',
        'con unos guantes de cuero fino',
      ],
      atributo: [
        'con una cicatriz en forma de estrella',
        'con ojos que brillan en la oscuridad',
        'con una cola hecha de fuego frío',
        'con la piel cubierta de escamas doradas',
      ],
      habilidad: [
        'que puede lanzar hechizos de fuego',
        'que puede hablar con los animales',
        'que tiene fuerza sobrehumana',
        'que puede volverse invisible',
      ],
      vehiculo: [
        'una carreta de madera',
        'un carruaje real',
        'una balsa de troncos',
        'un carro de guerra',
      ],
      arma: [
        'con una espada de doble filo',
        'con un arco largo',
        'con una lanza de roble',
        'con un hacha de guerra',
      ],
      planta: [
        'rodeado de enredaderas espinosas',
        'junto a un roble centenario',
        'entre flores silvestres moradas',
        'cerca de un árbol retorcido sin hojas',
      ],
      comida: [
        'sosteniendo una jarra de cerveza',
        'comiendo un trozo de pan con queso',
        'con un cuenco de estofado humeante',
        'sosteniendo una manzana roja',
      ],
      lugar: [
        'frente a un castillo en ruinas',
        'dentro de una taberna iluminada por velas',
        'en lo alto de una torre de piedra',
        'junto a un puente de piedra sobre un río',
      ],
      clima: [
        'bajo una tormenta de rayos',
        'con niebla espesa cubriendo el suelo',
        'durante una nevada silenciosa',
        'bajo un cielo rojizo al atardecer',
      ],
      material: [
        'hecho de oro macizo',
        'hecho de piedra tallada',
        'hecho de madera de roble',
        'hecho de hierro forjado',
      ],
      accion: [
        'mientras desenvaina su espada',
        'mientras lee un libro de hechizos',
        'mientras cabalga a toda velocidad',
        'mientras enciende una hoguera',
      ],
    },
  },
  {
    id: 'editorial',
    name: 'Editorial y cartoon',
    icon: 'assets/icons/cat-editorial.svg',
    banks: {
      personaje: [
        'un político con cara de circunstancia',
        'una abuela chismosa',
        'un oficinista estresado',
        'un influencer exagerado',
      ],
      criatura: [
        'un monstruo de closet tímido',
        'un fantasma torpe',
        'un duende de oficina',
        'un extraterrestre confundido',
      ],
      animal: [
        'un gato gordo',
        'un perro salchicha',
        'un pingüino regordete',
        'una gallina despeinada',
      ],
      objeto: [
        'un maletín gastado',
        'una taza de café gigante',
        'un paraguas roto',
        'un teléfono con la pantalla rota',
      ],
      ropa: [
        'con una corbata torcida',
        'con una bata de baño',
        'con un traje tres tallas más grande',
        'con calcetines de rombos desparejados',
      ],
      accesorio: [
        'con un reloj de pulsera enorme',
        'con una placa de identificación torcida',
        'con unos audífonos gigantes',
        'con un prendedor con forma de dona',
      ],
      atributo: [
        'con una papada enorme',
        'con lentes gruesos que agrandan los ojos',
        'con una sonrisa nerviosa exagerada',
        'con las cejas permanentemente levantadas',
      ],
      habilidad: [
        'que siempre llega tarde a todo',
        'que se tropieza con sus propios pies',
        'que grita en las reuniones',
        'que duerme con los ojos abiertos',
      ],
      vehiculo: [
        'un auto viejo y abollado',
        'una bicicleta oxidada',
        'un scooter eléctrico pequeño',
        'una patineta desgastada',
      ],
      arma: [
        'con un paraguas como si fuera espada',
        'con un matamoscas gigante',
        'con un megáfono',
        'con una regla de madera como arma improvisada',
      ],
      planta: [
        'junto a una planta de oficina medio muerta',
        'entre macetas de plástico desordenadas',
        'cerca de un árbol lleno de globos perdidos',
        'con un cactus torcido en el escritorio',
      ],
      comida: [
        'sosteniendo una dona a medio comer',
        'con un vaso de café para llevar',
        'comiendo fideos instantáneos de un vaso',
        'sosteniendo una hamburguesa gigante',
      ],
      lugar: [
        'en medio de un embotellamiento',
        'dentro de una oficina con cubículos apretados',
        'en la fila del supermercado',
        'en una sala de espera abarrotada',
      ],
      clima: [
        'bajo un sol que derrite el asfalto',
        'con lluvia que arruina el peinado',
        'en un día ventoso que vuela los papeles',
        'bajo un smog espeso',
      ],
      material: [
        'hecho de cartón corrugado',
        'hecho de plástico barato',
        'hecho de goma elástica',
        'hecho de papel reciclado',
      ],
      accion: [
        'mientras revisa el celular sin parar',
        'mientras derrama el café encima',
        'mientras discute por teléfono',
        'mientras firma papeles sin leerlos',
      ],
    },
  },
  {
    id: 'cienciaficcion',
    name: 'Ciencia Ficción',
    icon: 'assets/icons/cat-cienciaficcion.svg',
    banks: {
      personaje: [
        'un piloto de nave espacial',
        'una científica genética',
        'un explorador de otro planeta',
        'un soldado cibernético',
      ],
      criatura: [
        'un alienígena de tres ojos',
        'una criatura mutante radiactiva',
        'un enjambre de nanobots con forma animal',
        'un depredador de otro planeta',
      ],
      animal: [
        'un gato blanco',
        'un cuervo gris',
        'un perro pequeño',
        'un halcón marrón',
      ],
      objeto: [
        'un escáner portátil',
        'un dispositivo holográfico',
        'una esfera de energía',
        'un mapa estelar digital',
      ],
      ropa: [
        'con un traje espacial ajustado',
        'con una chaqueta futurista con luces led',
        'con un uniforme militar espacial',
        'con una bata de laboratorio',
      ],
      accesorio: [
        'con un visor de realidad aumentada',
        'con un implante en la sien',
        'con un collar con pantalla digital',
        'con guantes tecnológicos con botones',
      ],
      atributo: [
        'con un brazo biónico',
        'con ojos que emiten luz azul',
        'con piel metálica',
        'con un tercer ojo en la frente',
      ],
      habilidad: [
        'que puede teletransportarse',
        'que controla la tecnología con la mente',
        'que tiene visión de rayos x',
        'que puede hackear cualquier sistema',
      ],
      vehiculo: [
        'una nave espacial plateada',
        'un vehículo flotante',
        'un rover todo terreno',
        'una moto propulsada por reactores',
      ],
      arma: [
        'con una pistola láser',
        'con un sable de energía',
        'con un lanzallamas de plasma',
        'con un rifle de pulsos',
      ],
      planta: [
        'entre plantas bioluminiscentes',
        'cerca de árboles con hojas metálicas',
        'junto a un jardín hidropónico',
        'rodeado de esporas flotantes',
      ],
      comida: [
        'sosteniendo una bebida energética futurista',
        'comiendo una pastilla de comida concentrada',
        'con un tubo de nutrientes',
        'sosteniendo fruta cultivada en un invernadero espacial',
      ],
      lugar: [
        'dentro de una nave espacial',
        'en una estación orbital',
        'sobre la superficie de un planeta desértico',
        'en un laboratorio futurista lleno de pantallas',
      ],
      clima: [
        'bajo una lluvia ácida',
        'en medio de una tormenta de asteroides',
        'con gravedad reducida flotando en el aire',
        'bajo dos soles brillantes',
      ],
      material: [
        'hecho de metal cromado',
        'hecho de fibra de carbono',
        'hecho de vidrio reforzado',
        'hecho de aleación desconocida',
      ],
      accion: [
        'mientras pilota una nave',
        'mientras repara un robot',
        'mientras analiza datos en una pantalla holográfica',
        'mientras escapa de un peligro',
      ],
    },
  },
  {
    id: 'terror',
    name: 'Terror y misterio',
    icon: 'assets/icons/cat-terror.svg',
    banks: {
      personaje: [
        'un doctor de mirada perturbadora',
        'una niña que no parpadea',
        'un enterrador solitario',
        'un paciente de manicomio abandonado',
      ],
      criatura: [
        'un fantasma encadenado',
        'una sombra con forma humana',
        'un demonio de ojos rojos',
        'una criatura que se arrastra por las paredes',
      ],
      animal: [
        'un cuervo negro',
        'una rata gris',
        'un murciélago pequeño',
        'un gato negro',
      ],
      objeto: [
        'una muñeca de porcelana agrietada',
        'un espejo antiguo',
        'una caja de música oxidada',
        'un diario con páginas arrancadas',
      ],
      ropa: [
        'con un camisón manchado',
        'con una bata de hospital rasgada',
        'con un abrigo negro largo',
        'con un vestido de novia deshilachado',
      ],
      accesorio: [
        'con un collar con un relicario oxidado',
        'con guantes de cuero negro',
        'con un anillo con una piedra oscura',
        'con un antifaz de porcelana',
      ],
      atributo: [
        'con la piel pálida como la muerte',
        'con las manos cubiertas de sangre seca',
        'con una sonrisa que no debería existir',
        'con los ojos completamente negros',
      ],
      habilidad: [
        'que puede aparecer y desaparecer sin aviso',
        'que susurra en idiomas desconocidos',
        'que controla a otros con la mirada',
        'que nunca duerme',
      ],
      vehiculo: [
        'una ambulancia abandonada',
        'un tren fantasma detenido',
        'una carreta funeraria vieja',
        'un auto sin conductor',
      ],
      arma: [
        'con un cuchillo oxidado',
        'con un hacha manchada',
        'con unas tijeras enormes',
        'con una motosierra vieja',
      ],
      planta: [
        'entre árboles secos y retorcidos',
        'rodeado de enredaderas muertas',
        'junto a flores negras marchitas',
        'entre raíces que sobresalen del suelo',
      ],
      comida: [
        'sosteniendo una manzana podrida',
        'con un frasco de líquido oscuro',
        'sosteniendo un trozo de carne cruda',
        'con una taza de té frío olvidada',
      ],
      lugar: [
        'dentro de una casa abandonada',
        'en un cementerio cubierto de niebla',
        'en un sótano oscuro y húmedo',
        'frente a un hospital psiquiátrico en ruinas',
      ],
      clima: [
        'bajo una luna llena rojiza',
        'con niebla que no deja ver más allá de unos metros',
        'durante una tormenta eléctrica nocturna',
        'con un silencio antinatural en el aire',
      ],
      material: [
        'hecho de hueso',
        'hecho de madera podrida',
        'hecho de vidrio agrietado',
        'hecho de tela raída',
      ],
      accion: [
        'mientras camina arrastrando los pies',
        'mientras susurra algo inentendible',
        'mientras observa fijamente desde la ventana',
        'mientras escribe algo en las paredes',
      ],
    },
  },
  {
    id: 'mitologia',
    name: 'Mitología',
    icon: 'assets/icons/cat-mitologia.svg',
    banks: {
      personaje: [
        'un oráculo griego',
        'una sacerdotisa egipcia',
        'un guerrero vikingo',
        'un faraón momificado',
      ],
      criatura: [
        'un centauro',
        'una esfinge',
        'el lobo Fenrir',
        'un cancerbero de tres cabezas',
      ],
      animal: [
        'una serpiente del Nilo',
        'un águila dorada',
        'un toro sagrado',
        'un búho blanco',
      ],
      objeto: [
        'un cetro dorado',
        'una lira antigua',
        'un ánfora de barro',
        'una tablilla con jeroglíficos',
      ],
      ropa: [
        'con una toga blanca',
        'con una túnica egipcia bordada en oro',
        'con una armadura vikinga de cuero',
        'con un manto púrpura de emperador',
      ],
      accesorio: [
        'con un tocado con forma de serpiente',
        'con un brazalete de oro',
        'con una corona de olivo',
        'con un amuleto en forma de escarabajo',
      ],
      atributo: [
        'con un rayo en la mano',
        'con alas en los talones',
        'con la cabeza de un chacal',
        'con ojos que ven el pasado y el futuro',
      ],
      habilidad: [
        'que controla los rayos y truenos',
        'que puede transformarse en cualquier animal',
        'que guía las almas al inframundo',
        'que tiene fuerza para mover montañas',
      ],
      vehiculo: [
        'un carro tirado por caballos',
        'una barca solar egipcia',
        'un barco vikingo con proa de dragón',
        'un carruaje dorado de los dioses',
      ],
      arma: [
        'con un tridente',
        'con un martillo de guerra',
        'con un arco de plata',
        'con una espada envuelta en fuego',
      ],
      planta: [
        'junto a un olivo sagrado',
        'entre juncos del Nilo',
        'rodeado de laureles',
        'cerca de un árbol de la vida dorado',
      ],
      comida: [
        'sosteniendo una copa de néctar',
        'con un racimo de uvas',
        'sosteniendo pan y cerveza egipcia',
        'con una copa de hidromiel',
      ],
      lugar: [
        'en la cima del monte Olimpo',
        'dentro de una pirámide egipcia',
        'en el gran salón de Valhalla',
        'junto a las orillas del río Nilo',
      ],
      clima: [
        'bajo un cielo partido por rayos',
        'con arena levantada por el viento del desierto',
        'entre nubes doradas al amanecer',
        'bajo una aurora boreal',
      ],
      material: [
        'hecho de oro puro',
        'hecho de mármol blanco',
        'hecho de bronce antiguo',
        'hecho de piedra caliza',
      ],
      accion: [
        'mientras lanza un rayo desde su mano',
        'mientras cruza el río de los muertos',
        'mientras narra una profecía',
        'mientras lucha contra un monstruo marino',
      ],
    },
  },
  {
    id: 'estudio',
    name: 'Estudio de dibujo',
    icon: 'assets/icons/cat-estudio.svg',
    banks: {
      personaje: [
        'una persona leyendo un libro',
        'un anciano sentado en un banco',
        'una estudiante escribiendo en un cuaderno',
        'un hombre esperando el bus',
      ],
      criatura: [
        'un caracol de jardín',
        'una araña común',
        'una mariposa nocturna',
        'un escarabajo pequeño',
      ],
      animal: [
        'un gato doméstico',
        'un perro labrador',
        'una paloma común',
        'un caballo de granja',
      ],
      objeto: [
        'una taza de cerámica',
        'un libro de tapa dura',
        'una mochila escolar',
        'una cámara fotográfica',
      ],
      ropa: [
        'con un suéter de lana',
        'con una chaqueta de mezclilla',
        'con un vestido de algodón',
        'con una camisa a cuadros',
      ],
      accesorio: [
        'con lentes de lectura',
        'con un reloj de pulsera simple',
        'con una bufanda de lana',
        'con aros pequeños',
      ],
      atributo: [
        'con el pelo canoso',
        'con una expresión pensativa',
        'con arrugas alrededor de los ojos',
        'con una postura encorvada',
      ],
      habilidad: [
        'que toca el piano con destreza',
        'que dibuja con mucho detalle',
        'que cocina platos elaborados',
        'que teje a mano con rapidez',
      ],
      vehiculo: [
        'una bicicleta común',
        'un auto familiar',
        'un autobús urbano',
        'una patineta simple',
      ],
      arma: [
        'con un martillo en la mano',
        'con unas tijeras de jardinería',
        'con un cuchillo de cocina',
        'con un destornillador',
      ],
      planta: [
        'junto a una maceta de geranios',
        'entre árboles de un parque',
        'cerca de un jardín de hierbas',
        'con un florero de girasoles en la mesa',
      ],
      comida: [
        'sosteniendo una taza de café',
        'comiendo una tostada con mermelada',
        'con un plato de fruta fresca',
        'sosteniendo un vaso de jugo de naranja',
      ],
      lugar: [
        'en un parque tranquilo',
        'dentro de una cafetería con ventanas grandes',
        'en la sala de una casa',
        'en una biblioteca silenciosa',
      ],
      clima: [
        'en una tarde soleada',
        'bajo una llovizna suave',
        'en una mañana con niebla ligera',
        'en un día nublado de otoño',
      ],
      material: [
        'hecho de madera pulida',
        'hecho de cerámica pintada',
        'hecho de tela de algodón',
        'hecho de vidrio soplado',
      ],
      accion: [
        'mientras toma una taza de té',
        'mientras escribe en su diario',
        'mientras riega las plantas',
        'mientras camina con su perro',
      ],
    },
  },
];
